### ISSUE TITLE
ttree draw parsing

### ISSUE THREAD

**Issue by aminnj** [aminnj/pdroot#1]
```python
>>> from pdroot.parse import to_ak_expr
>>> to_ak_expr("sum(Jet_pt[:2])")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/namin/sandbox/dev/pdroot/pdroot/parse.py", line 148, in to_ak_expr
    Transformer().visit(parsed)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ast.py", line 262, in visit
    return visitor(node)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ast.py", line 317, in generic_visit
    value = self.visit(value)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ast.py", line 262, in visit
    return visitor(node)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ast.py", line 326, in generic_visit
    new_node = self.visit(old_value)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ast.py", line 262, in visit
    return visitor(node)
  File "/Users/namin/sandbox/dev/pdroot/pdroot/parse.py", line 124, in visit_Subscript
    if isinstance(node.slice.value, (ast.Constant, ast.Num)):
AttributeError: 'Slice' object has no attribute 'value'
```

**Comment by aminnj** [comment]
fixed by https://github.com/aminnj/pdroot/commit/3dd00e595ed9f4bab0f6aec3b8e13339e04f3a8b
